# Generated by Django 4.2.15 on 2025-08-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Middle Name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("customer", "Customer"),
                    ("account_executive", "Account Executive"),
                    ("teller", "Teller"),
                    ("branch_manager", "Branch Manager"),
                ],
                default="customer",
                max_length=25,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="security_answer",
            field=models.CharField(max_length=100, verbose_name="Security Answer"),
        ),
        migrations.AlterField(
            model_name="user",
            name="security_question",
            field=models.CharField(
                choices=[
                    ("maiden_name", "What is your mother's maiden name?"),
                    ("favorite_color", "What is your favorite color?"),
                    ("birth_city", "What is your birth city?"),
                    ("childhood_friend", "What is the name of your childhood friend?"),
                ],
                default="maiden_name",
                max_length=100,
                verbose_name="Security Question",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Username"
            ),
        ),
    ]
